### PR TITLE
Typpings for typescript.

### PR DESCRIPTION
**Pull request by nathan130200**
Add intellisence for typescript completitions.

### CODE REVIEW

**Review by emanuelfranklyn — DISMISSED** [review]

**Review by emanuelfranklyn — APPROVED** [review]

**Comment by emanuelfranklyn** [comment]
Can you please change the branch from release to main?

**Comment by nathan130200** [comment]
Ok

**Comment by emanuelfranklyn** [comment]
probably no problens will happen, since theres no variable name from theses branchs

**Comment by emanuelfranklyn** [comment]
just now i noticied than theres no problem to merge this, sorry about that 😢

**Pull request merged**
