### PR TITLE
Add Prettier

### PR DESCRIPTION
**Pull request by VietnameZe**
Added Prettier as mentioned in https://github.com/twitchapis/twitch.js/issues/7

### CODE REVIEW

**Review by emanuelfranklyn — APPROVED** [review]
Please fix identation on comments on class files, they should look like this:
```javascript
/**
 * Text
 * More text
 */
```
but they are like this:
```javascript
        /**
    * Text
    * More Text
    */
```

Edit: Markdown fixed

**Comment by VietnameZe** [comment]
@emanuelfranklyn you're fast 😀

**Comment by VietnameZe** [comment]
was it a problem with Prettier or a conflict with ESLint? 

similar issue of Prettier here: https://github.com/prettier/prettier/issues/648

**Comment by emanuelfranklyn** [comment]
I don't know, hope it doesn't change back to this strange way of make comments.

**Review by emanuelfranklyn — APPROVED** [review]
All Fixed, i hope

**Pull request merged**
